### ISSUE TITLE
Clean up `longlong.h`

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1031]
As
```
   N.B: This file has been adapted from code found in GMP 4.2.1.
```
can be found in `longlong.h`, I was wondering if it could be nice to revise `longlong.h` according to the newest GMP version to see if things can be sped up?

**Comment by tthsqe12** [comment]
Here is a list of things to cleanup:
1. @fingolfin says we cannot assume certain builtins are defined simply based on the architecture, and I believe it.
2. The indentation (i.e. in the fallback code) is attrocious.
3. Certain macros are defined if certain architectures are found. Then, to determine if the fallback is needed, a weird mix of conditions is used. When possible, we should just check if the macro itself if defined as the gaurd around the fallback.

**Comment by wbhart** [comment]
NO, ABSOLUTELY NOT!!

The latest GMP is NOT license compatible with Flint. Note Flint is distributed under LGPL V2+. GMP is licensed either GPL V2+ or LGPL V3+ as far as I recall. This is not equivalent or compatible with LGPL V2+ as I currently understand the LGPL.

Under NO circumstances may we take code from the latest GMP and nor should their code be referred to when making changes to our files.

I realise you were not aware of this. I am simply being very definite here so that there can be no misunderstandings on this very important legal issue!

**Comment by albinahlback** [comment]
Sorry for my late reply. Thanks for your input Bill, I was not aware of that those are not compatible! (But now I am ;-) )

Not to diverge to much from the topic, but is there a reason to use LGPL instead of GPL?

**Comment by wbhart** [comment]
Yes, we can discuss this on Friday and fill you in.

**Comment by albinahlback** [comment]
Don't think this really is relevant. And I think `longlong.h` is pretty good as it currently is.

To improve compile time, one could use an `.in` file to reduce the file size to only contain what the local system is. However, this would only constitute for a minuscule part of the compile time, and would not be worth the effort.
