### ISSUE TITLE
`_fmpz_new_mpz` but with how many limbs to allocate

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1062]
If one would like to do this, is it so simple to only change the line in `_fmpz_new_mpz` containing
```c
                mpz_init2(page_ptr + j, 2*FLINT_BITS);
```
to
```c
                mpz_init2(page_ptr + j, sizeof(mp_limb_t) * numlimbs);
```
or is it more complicated than this? Ping @wbhart

**Comment by wbhart** [comment]
Why change it? 2*FLINT_BITS is a constant and so doesn't need computing. The compiler can fill it in.

Also sizeof(mp_limb_t) is the number of bytes whereas mpz_init2 takes the number of bits. So this would be incorrect as written.

**Comment by albinahlback** [comment]
Sorry for being vague. I want to implement a function which does what `_fmpz_new_mpz` does, but allocates X amount of limbs/bits instead of allocating only 2 * FLINT_BITS bits. Do you know what one has to change in order to achieve this?

**Comment by wbhart** [comment]
Note that this would include a definition for our "single" module which uses our very complicated memory manager!

**Comment by albinahlback** [comment]
This is how I understand the current memory manager:

#### `_fmpz_new_mpz`
1. Check for free mpz's. If something was found, it returns that one.
2. Since nothing was free, we allocate a new block in memory.
3. For every page in this block, we for every "section" within this page initialize one `mpz_t` with size of `2 * FLINT_BITS` bits. (And something extra within this loop to be safe from garbage collectors, which one should be able remove from this loop by using `FLINT_USES_GC`?)

#### `_fmpz_clear_mpz`
1. Something about `count` within a `fmpz_block_header_s`, but I don't see how this counter can get non-zero for "regular" C-users of Flint. In other words, I don't see how everything can get cleared.

Anyway, with my lack of knowledge, it seems like the most straight forward way is to only call `mpz_init` and not `mpz_init2`, thus skipping to allocate a lot of 2 limb mpz's. In this way one could "reallocate" without having to reallocate stuff.

**Comment by albinahlback** [comment]
Is there any advantages to allocating a bunch of 2 limb mpz's when setting a new block? Does their limbs have a higher probability to get closer to each other and therefore promote locality?

**Comment by wbhart** [comment]
The memory manager amortises the cost of allocating multiple mpz structs, the only thing it can optimise. This makes a huge difference when dealing with many smallish integers. GMP is responsible for the internal allocation and we can't control that.

As for GMP itself, I imagine they optimise for the case of a small number of limbs, because almost all allocations are small. The system allocator already has quite a lot of smarts for this case and so this is best overall. I don't see any way to do better without writing a multithreaded allocator that plugs into GMP, which is almost impossible to do because only GMP knows what needs to be allocated and when.

If you care so much about this you could try talloc or any of the many malloc replacements out there. So far I didn't notice a reliable speedup that was worth it over what we have already done.

**Comment by wbhart** [comment]
As for our use of 2 limbs in our allocator, this was arrived at heuristically. If you are allocating an mpz at all, it is very, very likely it is 2 limbs and not one. After all, most 1 or 0 limb allocations would simply use a small. So by changing this back to zero, it would slow things down overall, though perhaps not for your particular application.

**Comment by albinahlback** [comment]
I thought about this. Perhaps one could get some tiny fraction more speed by optimizing `_fmpz_new_mpz`, but overall I think the memory manager is very good.

One could do some sorting so one knows which mpzs have enough limbs when calling "`_fmpz_new_mpz2`", but that would require sorting and so on. I don't think you would really gain anything when doing real computations.

Therefore I will close this. Thanks for your explanation Bill!
