### ISSUE TITLE
examples/fmpz_mod_poly.cpp does not compile

### ISSUE THREAD

**Issue by tj314** [wbhart/flint2#1083]
# Problem description
The example program examples/fmpz_mod_poly.cpp does not compile, while examples/fmpz_mod_poly.c compiles with no issues. To me, it seems like the primary issue is that a fmpzxx object is passed to the fmpz_mod_polyxx constructor whereas fmpz_modxx_ctx_srcref is expected. However, the [documentation](https://flintlib.org/doc/flintxx_functions.html#c.fmpz_mod_polyxx::fmpz_mod_polyxx) for the fmpz_mod_polyxx states that fmpz_expr is expected.

# Expected behavior
The example compiles.

# Observed behavior
The cpp version of the example does not compile. The C version compiles.

# Environment
I am using up to date Fedora 35 Workstation with the following packages installed via the package manager:
- flint v2.8.4
- flint-devel v2.8.4
- flint-static v2.8.4

# Steps to reproduce
```shell
g++ -std=c++17 fmpz_mod_poly.cpp -o main -lflint -lgmp -I/usr/include/flint
```
This command produced a compile error (see the attached file [compile-output.txt](https://github.com/wbhart/flint2/files/8218030/compile-output.txt)).

However, running
```shell
gcc -std=c17 fmpz_mod_poly.c -o main -lflint -lgmp -I/usr/include/flint
```
produces a working binary.

**Comment by wbhart** [comment]
Thanks for the report! I'll mark this to be dealt with for our Flint-2.9 milestone.

**Comment by wbhart** [comment]
Fixed in trunk.

As you probably guessed, the documentation is wrong, and in fact one must create an fmpz_modxx_ctx object (passing the fmpzxx to it) instead of passing the fmpzxx directly to the polynomial constructor.

I have updated the docs to hopefully correctly reflect this.

(Currently there is no fmpz_modxx module, so this is the only thing you can currently do with the context object.)
