### ISSUE TITLE
LLL module: Complete the list of functions that are heuristic in nature and might return with wrong answers

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#1090]
https://github.com/wbhart/flint2/pull/1089

**Comment by wbhart** [comment]
Is this ticket still valid? I see #1089 was subsequently closed. @tthsqe12

**Comment by tthsqe12** [comment]
So, the test code currently doesn't fail with test multiplier 1000. However, there are many heuristic functions that were not properly documented nor properly tested by the original author. The changes required were
https://github.com/wbhart/flint2/commit/3f8ffc9a4e83a8bd628abcf84b6b2846d78bc545

**Comment by wbhart** [comment]
Ok, well I'll close this issue. I think it is obvious that the double module can't possibly guarantee reduction.

Your PR fixed the documentation entirely, though I wouldn't have used the words "don't do their job". There's no assumption that they could be used unconditionally for this purpose. They exist for performance reasons (in fact are absolutely critical to the performance of the LLL implementation which is derived from Stehle's fplll program). I'd have preferred the documentation state this, rather than complain about them, as they are absolutely necessary functions.

**Comment by tthsqe12** [comment]
Ok, but I think the documentation should at least state that the functions are unreliable.
