### ISSUE TITLE
fmpz_poly_xgcd takes forever

### ISSUE THREAD

**Issue by rwst** [wbhart/flint2#112]
```
# include "fmpz_poly.h"

int main()
{
    fmpz_poly_t x , y , zero;
    fmpz_t r;
    fmpz_poly_init ( x ) ;
    fmpz_poly_init ( y ) ;
    fmpz_poly_init ( zero ) ;
    fmpz_poly_set_ui(x,2);
    fmpz_poly_set_ui(y,2);
    fmpz_poly_set_ui(zero,0);
    fmpz_poly_xgcd(r,zero,zero,x,y);
    fmpz_poly_print ( x ) ; flint_printf ( " \ n " ) ;
    fmpz_print ( r ) ; flint_printf ( " \ n " ) ;
    fmpz_poly_clear ( x ) ;
    fmpz_poly_clear ( y ) ;
    fmpz_poly_clear ( zero ) ;
}
```
Discovered with http://trac.sagemath.org/ticket/17675

**Comment by wbhart** [comment]
Thanks. I can confirm this is a bug. Just taking a look now to find the cause.

**Comment by wbhart** [comment]
Actually, this is not a bug. The documentation states that both input polynomials must be primitive. This is not the case for constant polynomials other than 1. For that case, the algorithm in fact works.

I realise the interface is slightly inconvenient. But it is correct.

**Comment by fredrik-johansson** [comment]
This seems too easy to run into by accident. Should we not change the function to compute the primitive part, and add fmpz_poly_xgcd_primitive for polynomials already known to be primitive?

**Comment by wbhart** [comment]
It's done on purpose.

xgcd(2, 2) has no possible output, since the resultant is 1.

We could raise an exception in such a case. But it's not a trivial fix,
since there's quite a few cases to consider, e.g. it's ok if the inputs are
coprime integers (thought of as elements of the polynomial ring), but not
if they are not coprime. And it's not completely clear what should happen
in other rings.

Essentially bezout just didn't think this through when he came up with his
"theorem".

Bill.

**Comment by wbhart** [comment]
I think the best thing to do might be to write an fmpz_poly_xgcd that
disallows constant inputs unless they are primitive (i.e. 1). This will not
screw up the existing interface.

For non-constant inputs we could then do something more general.

If content(a) = c1 and content(b) = c2 then if
fmpz_poly_xgcd_modular(primitive_part(a), primitive_part(b)) returns r, s, t
we could return r*c1^(length(b) - 1)*c2^(length(a) - 1), s*c1^(length(b) -
2)*c2^(length(a) - 1), t*c1^(length(b) - 1)*c2^(length(a) - 2).
