### ISSUE TITLE
powmod2_preinv test fails

### ISSUE THREAD

**Issue by isuruf** [wbhart/flint2#219]
```
powmod2_preinv....FAIL:
a = 1605852564869, exp = 246441, d = 24509316
r1 = 12161785, r2 = 13860413
```

This is with the latest git commit of flint2 with gcc 5.2.1

**Comment by wbhart** [comment]
That's interesting. I just checked out trunk on my machine and don't see
this. It's also passing the continuous integration tests.

I tested with the particular values that fail for you and there is no
problem here. I also checked it with valgrind, and there are no issues
there, so I don't think it is an uninitialised value.

Of course we have recently changed this function, so a real bug is not
impossible. But I wonder if you could try checking out a clean copy from
trunk or doing make clean and rebuilding. I don't think this test should be
failing.

I will however commit a missing #include. I don't think that is the issue
though.

Bill.

**Comment by isuruf** [comment]
I cleaned the repo and get the same error.
With flint-2.5.2 I don't get the error when running `make check`, but when tested with the particular values, it fails.
Can you post a git commit before the recent changes that I can try?

**Comment by wbhart** [comment]
66d6d38de should be the commit prior to the one where this function was
modified.

8a3e1a962 should be before all the recent related changes.

It's definitely our value and not the GMP value which is incorrect.

What sort of machine does this happen on?

**Comment by isuruf** [comment]
Error is there in 8a3e1a9623804bcf9690c35307acd99be1279339. (I had to run `powmod2_preinv` manually because `revbin` segfaults before `powmod2_preinv` in `make check`)

I'm running this on a Intel(R) Core(TM) i5-5200U running 64-bit Ubuntu 15.10 with GMP and MPFR from Ubuntu repositories.

**Comment by wbhart** [comment]
Could you try 1cd3e45 and 49221c8. These are before and after a slightly
older set of changes that could potentially have caused the issue.

It's a bit mystifying, since if it passes on my machine, it should on
yours. Though I am sure it will turn out to be a bug in some of the commits
I made in November. Just why it doesn't cause a failure on my machine
remains to be seen.

**Comment by wbhart** [comment]
I also pushed a change to the most recent test code to print out the
precomputed inverse on failure. We can look at this to see that the
precomputed inverse is being computed correctly. That will help narrow down
where the bug could be.

Bill.

**Comment by isuruf** [comment]
Still fails with the master and also  1cd3e45.
```
powmod2_preinv....FAIL:
a = 12062733498991, exp = 999328254200441697, d = 17645, dinv = 15810150786438625621
r1 = 16078, r2 = 5096
```
````
powmod2_preinv....FAIL:
a = 1605852564869, exp = 246441, d = 24509316, dinv = 6807735473687451933
r1 = 12161785, r2 = 13860413
```

**Comment by wbhart** [comment]
Thanks. Both of the precomputed inverses are computed correctly, so the
problem must be in n_powmod2_preinv or n_mulmod2_preinv. However, if that
is the case, it's been a bug for many years, and surely we would have seen
it somewhere before now.

However I don't see any bugs in either of those files.

As I can't reproduce the bug, even when I input the specific values, I am
beginning to suspect you have hit a compiler bug or even a hardware issue.

Could you try modifying the -O2 in your Makefile (not Makefile.in). Simply
remove the -O2 altogether and see if the issue goes away.

Bill.

**Comment by wbhart** [comment]
I forgot to mention: don't do configure again after modifying Makefile, as
configure rewrites that file.

**Comment by isuruf** [comment]
Nothing changes after removing -O2. I'll try again with a new GMP and MPFR built.

**Comment by wbhart** [comment]
I don't think GMP or MPFR are relevant here. They are definitely returning
the correct answer.

I'm still puzzled as to why flint-2.5.2 passes but 1cd3e45
<https://github.com/wbhart/flint2/commit/1cd3e456a18ee8ad85b71e1f7bd7be7af46ad6ad>
 fails.

Flint-2.5.2 was released August 2015 and the only change to
n_powmod2_preinv in the interim was whitespace. There were no changes to
n_powmod_ui_preinv before that commit and no changes to n_mulmod_preinv
between the release and the commit. Similarly there were no changes to the
test code in that time period.

As far as I can see, there is no reason for the failure you are observing.
I've run out of reasonable hypotheses.

The next thing would be to insert printfs throughout n_powmod2_preinv and
run it through for the specific failing case you have and we'll see if we
can catch it in the act of giving a wrong answer somewhere.

You can write

flint_printf("n = %wd\n", n);

if you want to print one of the ulong values.

Perhaps try printing each of the inputs and the output of each of the three
n_mulmod_preinv function calls in n_powmod_ui_preinv (in
ulong_extras/powmod_ui_preinv.c), and we may be able to find a failing case
for n_mulmod_preinv starting from the failing n_powmod2_preinv case you
have. Then we can trace n_mulmod_preinv through and see where it is going
wrong.

If you send me the outputs I can check where the error is occurring in each
case.

I would do this with the latest trunk.

**Comment by wbhart** [comment]
@isuruf Does this problem still occur for you? We did fix some fallback code in longlong.h which could have caused this. On the other hand, I don't understand why that would be selected on your machine.

In any event we are going to need some more information, as we can't replicate this.

Another possibility that occurs to me is that some version of GMP has a faulty _clz_tab and it is being picked up. This sort of thing has happened before, and would be fixed with a different version of GMP. So you might possibly be right about trying that.

**Comment by isuruf** [comment]
I'm sorry, but I don't recall any details about this. If appveyor tests all pass, feel free to close this one.

**Comment by wbhart** [comment]
I'll wait and see if any of the disabled tests still fail. Otherwise I'll close this.

**Comment by isuruf** [comment]
Wait, this was on Ubuntu, but I haven't seen this error lately.
