### ISSUE TITLE
Bug in assigning fmpqxx to fmpq_polyxx

### ISSUE THREAD

**Issue by isuruf** [wbhart/flint2#223]
Following doesn't work.

```
flint::fmpqxx e(2, 5u);
flint::fmpq_polyxx p = e;
```

But following does work.

```
flint::fmpqxx e(2, 5u);
flint::fmpq_polyxx p;
p = e;
```

**Comment by wbhart** [comment]
Again, someone with some more C++ fu that me will have to do this one, e.g. @tthsqe12

**Comment by tthsqe12** [comment]
I will have a look at this type of stuff, but I can't guarantee anything right now.

**Comment by tthsqe12** [comment]
I do not think this is a bug.
(1) `foo a = b` tries to convert `b` to a `foo` using an implicit conversion before calling the constructor for `foo`.
(2) `foo a; a = b` uses an overload of the assignment operator after `a` is constructed.

Since the test code for flintxx eschews form (1) for form (2), we must conclude that implicit conversions are not part of the design of flintxx.

**Comment by wbhart** [comment]
That sounds correct, actually. There are a few design decisions like this which are mildly inconvenient, but more or less intentional, for good reasons.
