### ISSUE TITLE
Make check failure

### ISSUE THREAD

**Issue by isuruf** [wbhart/flint2#255]
```
pollard_brent.... 
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
FAIL : Pollard Rho - Brent failed too many times (2 times)
```

This is a 32 bit build on Windows in MSYS2 env, MinGW-w64 toolchain 

Full log is here, https://ci.appveyor.com/project/isuruf/flint2/build/1.0.11/job/6nw8yfp5qd8jwfgi

**Comment by wbhart** [comment]
Thanks. It's safe to simply increase the percentage of cases that are
allowed to fail on 32 bit machines. I assume it was running many more than
two times.

**Comment by isuruf** [comment]
Yes, it was running 40 times and failed 2 times, but the test is designed to fail if there are more than 1 failure.

**Comment by wbhart** [comment]
Then the test can safely be changed to allow 2 failures. It's only supposed
to check that the function is useful in a majority of cases. I guess it was
set to a value that made the test code pass.

Technically the number of failures should be related somehow to the number
of iterations. And if the number of iterations is related to
flint_test_multiplier() then so should the number of failures be related to
it.

Anyway, this is brand new code which I am delighted to hear works on 32 bit
machines.

**Comment by isuruf** [comment]
Will do the change. Actually number of test cases is `40*flint_test_multiplier()` and only `flint_test_multiplier()` failures are allowed. 
It's a 64 bit machine, but built using MinGW-w64 i686 toolchain.

**Comment by isuruf** [comment]
Another failure
```
get_mpn.... 
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
conversion failed.
n : 2251799813161472
converted value : 9671388110172963982541312
./Makefile.subdirs:91: recipe for target '../build/fmpz/test/t-get_mpn.exe_RUN' failed
make[1]: *** [../build/fmpz/test/t-get_mpn.exe_RUN] Error 3
```

**Comment by wbhart** [comment]
I think I've seen this one before. I don't know if I managed to figure out
what caused it.

**Comment by wbhart** [comment]
I fixed a related failure in n_factor_ecm today. I haven't seen either of the other failures yet.

**Comment by wbhart** [comment]
The first issue is fixed in trunk.

The second issue is a mystery. This is a particularly simple function which simply allocates an array, copies some limbs into it and returns the number of limbs. The test code had some dodgy bits, which I've fixed. But I don't think any of them are relevant to the bug.

I've added a regression test for this specific value of n with some printing of various things to see if we can identify the problem.

@isuruf Could you possible run this again on your 64 bit machine with the i686 toolchain (so that FLINT_BITS==32) and see if the problem still exists. I suspect this can only be a compiler bug as the code itself is trivial.

**Comment by wbhart** [comment]
@isuruf Don't worry, I can see that you fixed the test code, which was using 64 instead of 32 for the number of bits on a 32 bit machine, which explains the bug. If the CI passes now, this is fixed ages ago.
