### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [wbhart/flint2#275]
Seems it has been almost a year since the last release was made. Would it be possible to get a new release?

cc @fredrik-johansson @isuruf

**Comment by wbhart** [comment]
There's a few things we need to do before we can do a release. We need to
thoroughly check the is_prime_aprcl code that was committed. There's a
bunch of tickets that need closing. And I want to get a working quadratic
sieve.

All of that is going to take time. Fortunately, I'm working 25% on the
OpenDreamKit project, which will allow me to spend time on the quadratic
sieve. I haven't got much other time at the moment though, unfortunately.

Bill.

**Comment by isuruf** [comment]
Ping. Let me know if I can help with anything to get a release out.

**Comment by wbhart** [comment]
There's still more to be done. Apparently aprcl causes crashes. The
quadratic sieve needs to create a temporary file instead of putting a file
in the current directory. I'm still working on the multivariate arithmetic.
And none of the currently open tickets have been closed. But I have at
least gotten the QS working. So we are one step closer to a release.

I'll have a check if there are any tickets in my email inbox that haven't
actually been converted into GitHub tickets, in case you want to work on
them. I'll also make a Flint 2.6 milestone on GitHub and put all the
blockers in the Milestone.

**Comment by wbhart** [comment]
Duplicate.
