### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by adammaj1** [wbhart/flint2#303]
Hi, 

After make check one test failed :
```
lll_d_heuristic....PASS
wrapper_with_removal....PASS
lll_d_heuristic_with_removal....PASS
heuristic_dot....FAIL:
expo1 = 198, expo2 = 199
d1 = 6.03268e-120, d2 = 2.01654, d3 = 1.06274, d4 = 3.07929
3.54206e-12
../Makefile.subdirs:91: polecenia dla obiektu '../build/fmpz_lll/test/t-heuristic_dot_RUN' nie powiodły się
make[1]: *** [../build/fmpz_lll/test/t-heuristic_dot_RUN]: Przerwane
make[1]: Opuszczenie katalogu '/home/a/flint2/fmpz_lll'
Makefile:212: polecenia dla obiektu 'check' nie powiodły się
make: *** [check] Błąd 2
```

Adam

**Comment by wbhart** [comment]
For what it's worth, heuristic_dot is going to be removed from use in
Flint. I can't recall if I've made this change in trunk or not, but I will
make the change soon. On the other hand I believe this failure is harmless
and can probably be ignored. I will try to fix the issue soon.

Bill.

**Comment by wbhart** [comment]
I have checked and this function is no longer used in the Flint LLL. You
could just remove the test file entirely if you just want to get past it
for now.

Bill.

**Comment by adammaj1** [comment]
OK. Now all test passed

**Comment by wbhart** [comment]
I've updated the test code for fmpz_lll_dot_heuristic. The function it
tests is still used in the LLL, but it now uses an older version of
_d_vec_dot_heuristic. This makes the LLL much faster, but doesn't have such
tight guarantees. In order to accommodate this, I changed the test function
to be very slightly more relaxed. I ran it 10 times and it didn't fail now,
but let me know if you still get a failure.

The exact amount of numerical noise it allows is certainly not critical.
The test is just supposed to make sure the answer isn't completely wrong.
And in fact the error you reported shows that it was correct to the
precision of printing, so it is clear the function is working as expected
on your machine, i.e. definitely nothing to worry about.

Bill.
