### ISSUE TITLE
Improvements for tree Chinese Remaindering

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#320]
Currently at every level of the tree CRT we compute m^-1 mod n and n^-1 mod m for each pair of coprime moduli. Both can be computed efficiently using a single xgcd. This should speed up CRT considerably.

Suggested by Claus Fieker.

**Comment by fredrik-johansson** [comment]
I think the CRT and reduction could be improved in more ways, e.g. by switching to iteration to do n x 1 limb operations (maybe with mpn code) instead of recursing all the way.

**Comment by fredrik-johansson** [comment]
We could also use the fmpz_preinvn functions to speed up fmpz_mod operations.

**Comment by fredrik-johansson** [comment]
* The multi_CRT and multi_mod functions should be redesigned to use basecase code like in fmpz_mat_mul_multi_mod
* With a better basecase, the comb structure and tree traversal could be simplified to use simple recursive calls instead of the padded power-of-two array structure with its complicated bookkeeping (the comb_temp structure could also probably be thrown away completely). Balanced splitting without the power-of-two jumps should itself improve performance
* I have already tested using fmpz_preinvn and it did not give a speedup at all
* The incremental CRT functions should also be optimized in terms of overhead

**Comment by wbhart** [comment]
I only see a single fmpz_invmod per pair of moduli. In any event (f)mpz_xgcd computes the other one via the bezout relation anyway, so I don't see anything to be gained here.

I'm going to rename the ticket to reflect that we'd like to make the changes suggested by @fredrik-johansson  and bump to the next release.

**Comment by wbhart** [comment]
Done by @tthsqe12
