### ISSUE TITLE
Root finding in finite fields

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#354]
Jean Kieffer has requested a function for root finding of polynomials over a finite field.

**Comment by tthsqe12** [comment]
I can probably do this. The only question is how to return the answer when the user has no idea how long it is going to be. Flint has no std::vector<ulong> class unless you count nmod_poly, where I would consider storing the roots of a poly as the coeffs of another poly an abuse of the type.

**Comment by thofma** [comment]
How about the user supplies an array with enough space and the function returns the number of roots? This is how it is done for some of the factoring functions, e.g. nmod_poly_factor_distinct_deg.

**Comment by tthsqe12** [comment]
> the user supplies an array with enough space.
I believe this to be bad design. Fmpq_get_cfrac suffers the same problem, which renders the function almost useless. It seems ddf returns the answer in a proper type. I think there really should be resizable stdvector-like classes in fling fir at least ulongs and fmozs. Maybe the interface fir fmpq get cfrac coukd change too?

**Comment by tthsqe12** [comment]
Oh, I see the ddf does indeed have issues as well. What a mess.

**Comment by wbhart** [comment]
I must be missing something. Why not use a factor struct, and just resize the space as needed in a geometric progression.

I'm happy if you want to use a special root struct instead to save having to put linear factors in.

Overcomplicating the design of Flint with a standard vector type is not a great idea.

**Comment by fredrik-johansson** [comment]
The overhead of overallocating an array would be negligible compared to actually computing the roots. If you don't want to do this, you could use either the interface

slong function(**ptr, ...)

or

ptr * function(slong * len, ...)

to output a length as well as a pointer to a new vector (which then has to be freed by the user).

I suppose a factor struct would make sense in order to output roots with multiplicities.

I'm not sure what I would prefer myself. I'm generally hesitant to introduce new data structures that merely act as containers.

**Comment by wbhart** [comment]
It's really not a good idea to have unmatched init/clear's. So having a function that leaves something for the user to clean up is just asking for trouble.

**Comment by tthsqe12** [comment]
I don't see any resolution here. For finite fields Fq, we can say the number of roots is bounded by min(q, deg(f)), thus we could ask the user to pass in a pointer to an array of this size, and return the actual size. Similarly for fmpq_get_cfrac there is an easy bound on the number of terms. I can do this approach, but it strikes me as another one-off design in flint and I don't like inconsistency in the official interfaces.
The reason is as follows. Suppose someone comes along and wants root finding not only in Z/pZ, but also in Z/nZ for any integer n. Now the "let the user supply an array bigger than the answer possibly could be" does not work, and the interfaces fir rootfinding over Z/pZ and Z/nZ must diverge.

**Comment by tthsqe12** [comment]
@wbhart I am not sure I understand your first post. A specialized struct to hold the roots of a T_poly_t would be a T_vector_t, which would be a struct holding a resizable array with elements of type T. T_vector_t would be remarkably similar to T_poly_t, which makes the idea of abusing the latter for the former an attractive possibility.

**Comment by thofma** [comment]
No matter what you do, please also return the multiplicities of the roots, either in the exponent of the linear factor if you abuse T_poly_factor_struct (or the degree of the monomials if you use T_poly_t?).

**Comment by tthsqe12** [comment]
@thofma  is the multiplicity of a root of a polynomial over Z/4Z a sensible concept?

**Comment by thofma** [comment]
Yes, I think it is well-defined. The degree of polynomials is multiplicative if one of the factors is monic (or has invertible leading coefficients). Also you can divide by monic polynomials, etc. Apply with (x - a) and you are done.

**Comment by wbhart** [comment]
@thofma I don't think I mentioned using a T_poly_t at all. I was initially suggesting to use a T_poly_factor_t struct, i.e. put the roots as linear factors into a factor struct. I then realised this would be a bit inefficient, so some other struct that holds a resizeable array of roots would be better.

I don't mind if there if vectors are used for this at a lower level, though vectors in the actual vec modules are not really resizable in their current form.

But at the higher level I would like not like to see an fmpz_poly_t for example used to hold the roots of an fmpz_poly_t. This sort of approach is widely criticised elsewhere. At the higher level there is some mathematical meaning given to the various structs we use.

I'm also wary of overcomplicating Flint with multiple levels of abstraction. It's survived as long as it has by being very flat in its development model. We don't have generic objects, we don't have incredibly deep hierarchies of abstraction and I've not been pushing templating and so on. I'd like to keep it simple.

The design elsewhere has been to keep things as simple as possible at a lower level, i.e. a T* and length and to introduce a few simple functions and a higher level struct that makes resizing straightforward (init, clear, realloc, fit, etc.)

**Comment by tthsqe12** [comment]
Hmm. Ok. If the multiplicities are desired as well, I am at a loss for how to return the answer except as a T_factor_t with factors of the form x-r_i and multiplicities in the exponents.

Z/nZ will be for another time as this ticket is simply about finite fields. For Z/nZ I think I have to find the roots r_i of f(x) in Z/nZ first, then find the highest power of x-r_i that divides f(x). No? Do the divisibility functions work in this case?

**Comment by thofma** [comment]
@wbhart Where did I say that you mentioned `T_poly_t`? I just said that one should try to keep track of multiplicities.

@tthsqe12 You might be lucky and they work, since the divisor is monic.

**Comment by tthsqe12** [comment]
I was the one who wanted to abuse T_poly_t as a T_vector_t so we don't have a bunch of new types in flint.
Maybe we are approaching this entirely wrong. Since flint lacks the abstraction to return complicated answers, why not implement a bunch of primitives that are useful for root finding, but do the actual root finding in a language will proper types?

**Comment by wbhart** [comment]
Sorry @thofma, I misread the name. It was @tthsqe12

**Comment by wbhart** [comment]
I really think this is a special case where there is a mathematical meaning to the output. It's not just a list of elements of the coefficient ring, but a list of pairs of elements and multiplicities. We already have the factor struct, so we could use that (it's just a limiting case where the degrees are 1), or we introduce a special T_root_list_t.

Probably the actual cost of finding the roots far outweighs the inefficiencies of using a factor struct and we should just use that. At least it isn't mathematical nonsense.

I'm also not sure what primitives we could provide that would enable efficient computations of roots in a higher level language, especially over Z/pZ. I don't personally favour that approach. It also means that other users of Flint as a C library, in a C program, don't get the benefit.

The only thing I'm really objecting to is having some kind of multilayer approach where we have abstractions on abstractions. Flint is not supposed to have genericity. That is certainly for higher level languages.

**Comment by tthsqe12** [comment]
Alright. The answer is going in a T_factor_t. The behaviour over a field will the same as a call to T_factor followed by a deletion of nonlinear factors.

**Comment by wbhart** [comment]
Added by @tthsqe12 in trunk.
