### ISSUE TITLE
Tag releases on github

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#406]
The releases don't get tagged on github, so:
- they don't appear there ;
- it's not clear which commit is the official version.

Could you tag them?

**Comment by wbhart** [comment]
The releases are in branches.

**Comment by SnarkBoojum** [comment]
Yes, and this is about tags : tags are on a specific place, and branches go forward.

**Comment by wbhart** [comment]
The only reason the release branches should be moving forward is for
patches which are added to a branch, e.g. 2.1.0 becomes 2.1.1, etc. There
isn't any value in 2.1.0 after 2.1.1 is released.

**Comment by SnarkBoojum** [comment]
I know that, but nothing will prevent an accidental commit to a release branch, while one really has to move out of its way to move a tag : that's why projects use tags for releases : they have the branch 2.1, and on this branch, tags for 2.1.1, then 2.1.2, etc.

**Comment by xu-cheng** [comment]
@wbhart 

Please consider to tag the release. It has many benefits:

* A tagged release in GitHub means the ability to download source code in a tar archive instead of git clone. Especially, when you consider that the latest release listed in http://www.flintlib.org/downloads.html is still flint 2.5.2, where the one in the Github branch is 3.0. This is very confusing to the end users.

* A tag means a freezed checksum for that release (either as git commit hash, or checksum of tar file created by GitHub). This guarantees the security of the source code, since otherwise there is no prevention against malicious attacker adding new commits in case of security breach. This is also highlighted  by @SnarkBoojum.

* The checksum is also required for a reproducible build for this software or any other projects depending on flint. More information can be found at https://wiki.debian.org/ReproducibleBuilds.

* A tag is required for nearly all package managers. It is worth noting that no package manager currently includes flint.

Finally, it should be noted that tagging the release is the standard procedure for the majority of open source projects.

I hope that I could connivence you that tagging release can benefit users in many ways.  Also would you consider to publish a new release. The current release at http://www.flintlib.org/downloads.html is several years old.

**Comment by wbhart** [comment]
We will tag releases starting with flint-2.6. However, these will be tagged on the branches, not on trunk, as we primarily do releases using branches so that bug fixes can be backported to the most recently released version without holding up new development on trunk.

**Comment by SnarkBoojum** [comment]
As long as they are tagged, I think github will detect them as such, and hence notify me about them.

**Comment by dimpase** [comment]
Well, I just found this issue, and yes, please tag, and not only 2.6, but previous versions too.

**Comment by wbhart** [comment]
We don't have tags for previous releases, but branches. We won't be able to reliably tag previous releases.

**Comment by SnarkBoojum** [comment]
You can tag whatever commit you want on whatever branch you want, as far as I know.

**Comment by wbhart** [comment]
What I mean is that the knowledge of which commit corresponded to which release is long gone. I don't think I could reliably go back and tag the correct commits.

Unlike many other projects, we don't maintain past releases. We do large, solid releases which try to fix problems users reported with previous releases, then backport important patches from trunk to the most recent release branch only (and increment the patch number).

In my personal opinion, the superstition regarding releases, tags, versions and so on, appears a little over-the-top for mathematicians like myself. I mean, just today GCC crashed my machine multiple times and internally segfaulted. The last time I updated Ubuntu, the upgrade process crashed half way through and I am now stuck between Ubuntu versions. The German language app I used crashed multiple times today and Chrome crashed twice. Microsoft even bricked my laptop a few weeks ago during a live software update.

Our little maths package is going to be broken. Very broken. No amount of superstition is going to change that.

I'll tag releases and release candidates starting with flint-2.6.0. But I'm pretty sure people will be asking me to do something else instead by the time the next release comes along.

**Comment by dimpase** [comment]
The point is reproducibility. If someone computed something with Flint, 10
years down the road it ought to be reproducible. Messing up releases is
very unhelpful for such a task. Flint x.y.z+no longer identifiable patches
really is a problem.

**Comment by wbhart** [comment]
Done for this release.
