### ISSUE TITLE
Exception (FLINT memory_manager). Unable to allocate memory.

### ISSUE THREAD

**Issue by akrsnr** [wbhart/flint2#428]
It's really amazing. I check many times indexes but I can't see out of range. But I get the error,

Exception (FLINT memory_manager). Unable to allocate memory.

How can it be overcome?

**Comment by wbhart** [comment]
One possible way to solve this problem is to ask someone who knows about
Flint to look at your code. For example, you could post the code on the
flint-devel list and see if anyone can see something wrong with it.

Reporting this as a bug without any information about it whatsoever, or
even knowing if it is a bug in Flint and not in your code, is not really
helpful.
