### ISSUE TITLE
OpenMP pragma incorrect according to Clang

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#479]
The following problem occurs, at least on recent Clang (gcc seems indifferent).

```
//home/travis/build/Normaliz/Normaliz/local/include/flint/ulong_extras.h:123:27: error: variable '_flint_primes' cannot be threadprivate because it is thread-local
#pragma omp threadprivate(_flint_primes, _flint_prime_inverses, _flint_primes_used)
                          ^
/home/travis/build/Normaliz/Normaliz/local/include/flint/ulong_extras.h:119:33: note: '_flint_primes' declared here
extern FLINT_TLS_PREFIX ulong * _flint_primes[FLINT_BITS];
                                ^
/home/travis/build/Normaliz/Normaliz/local/include/flint/ulong_extras.h:123:42: error: variable '_flint_prime_inverses' cannot be threadprivate because it is thread-local
#pragma omp threadprivate(_flint_primes, _flint_prime_inverses, _flint_primes_used)
                                         ^
/home/travis/build/Normaliz/Normaliz/local/include/flint/ulong_extras.h:120:34: note: '_flint_prime_inverses' declared here
extern FLINT_TLS_PREFIX double * _flint_prime_inverses[FLINT_BITS];
                                 ^
/home/travis/build/Normaliz/Normaliz/local/include/flint/ulong_extras.h:123:65: error: variable '_flint_primes_used' cannot be threadprivate because it is thread-local
#pragma omp threadprivate(_flint_primes, _flint_prime_inverses, _flint_primes_used)
                                                                ^
/home/travis/build/Normaliz/Normaliz/local/include/flint/ulong_extras.h:121:29: note: '_flint_primes_used' declared here
extern FLINT_TLS_PREFIX int _flint_primes_used;
```

Probably the offending line should be removed when TLS is enabled.

**Comment by peter-frentrup** [comment]
This error was partly fixed with the merged-in PR #489 by @martinra. However, in `compute_primes.c`, there still is an unconditional
> #pragma omp threadprivate(_flint_primes, _flint_prime_inverses, _flint_primes_used)

I am observing sporadic crashes due to double-free in `n_cleanup_primes()` when calling `flint_cleanup()` from multiple threads. I guess that the compiler (MSVC on x64) saw "omp threadprivate" in one translation unit, but not in the other and thus compiled variable access differently in `n_compute_primes()` and `n_cleanup_primes()`.

I think `#pragma omp threadprivate ...` should be removed from `compute_primes.c` unconditionally, no?

**Comment by peter-frentrup** [comment]
I am using MSVC. Your original issue mentioned Clang.

It turned out that I did not compile with thread-local storage enabled, because cmake did not define HAVE_TLS in `config.h`. Consequently, `n_cleanup_primes()` acts on global data without any lock protection (unlike `n_compute_primes()`). 

So the superfluous `#pragma omp threadprivate` line might cause no harm, but it seems that we need
```
#if FLINT_REENTRANT && !HAVE_TLS
    pthread_once(&primes_initialised, n_compute_primes_init);
    pthread_mutex_lock(&primes_lock);
#endif
```
with appropriate unlocking at the end in `n_cleanup_primes()`, too. Probably the easiest way to do so would be to merge `compute_primes.c` and `cleanup_primes.c`.

Additionally, there should be some feature detection for HAVE_TLS in `CMakeLists.txt`.

I will investigate further, but recompiling the whole project takes several hours on my machine.

**Comment by wbhart** [comment]
We will be removing OpenMP support in favour of pthreads, so this will fix itself.
