### ISSUE TITLE
Any possible improvement on matrix multiplication?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [wbhart/flint2#605]
We found the multiplication of big matrices costs quite some time. For example
```
 flint::frandxx state;
 flint::nmod_matxx mmm = flint::nmod_matxx::randtest(20000,20010,mp_limb_t(11),state);
 flint::nmod_matxx mmm2 = flint::nmod_matxx::randtest(20010,20012,mp_limb_t(11),state);
 flint::nmod_matxx mul_temp( mmm*mmm2 );
flint::swap( mmm, mul_temp );
```
And the multiplication operation cost about 4 minutes. Also the "set_rref()" also cost tens of minutes on big matrix. So we were wondering if there is some approach to faster operation. 
Thank you.

**Comment by wbhart** [comment]
Yes, BLAS can be used. However, it is not implemented in Flint. It has been a longstanding ticket which we have not found time to work on (it is quite difficult).

**Comment by zhaoli-IHEP** [comment]
> Yes, BLAS can be used. However, it is not implemented in Flint. It has been a longstanding ticket which we have not found time to work on (it is quite difficult).

Thank you for the reply. 
I am trying to test with boost ublas library. However, I am not sure how to convert FLINT matrix to the ublas matrix. For example
```
  flint::frandxx state;
  boost::numeric::ublas::identity_matrix<flint::nmodxx> bb(3);
  flint::nmod_matxx ff = flint::nmod_matxx::randtest(3,3,mp_limb_t(11),state);
  for( int rr = 0; rr < 3; ++rr ) {
    for( int cc = 0; cc < 3; ++cc ) {
      bb(rr,cc) = ff.at(rr,cc);
    }//endfor cc
  }//endfor rr
```
This code fails at compilation. It seems "bb(rr,cc) = ff.at(rr,cc);" is not allowed.

**Comment by zhaoli-IHEP** [comment]
> Yes, BLAS can be used. However, it is not implemented in Flint. It has been a longstanding ticket which we have not found time to work on (it is quite difficult).

Thank you for the reply.
I am trying to test with boost ublas library. However, I am not sure how to create the ublas matrix for flint::nmodxx. For example
```
boost::numeric::ublas::matrix<flint::nmodxx> bb(3,3);
```
The code like this does not work. Could you give me more hints?

**Comment by wbhart** [comment]
Unfortunately, I am out of my depth on the C++ questions. I  don't know anything about Boost and very little about what may be wrong with the C++ wrapper.

However, I am writing some threaded code for the matrix multiplication. I'm not sure if it will give an impressive speedup, but even with one thread it is more efficient and gives a 20% speedup. On my 4 core laptop I get approximate 2.5x speedup on top of that with 4 threads.

I should be mostly done with the parallel multiplication code tonight, but it'll be a little longer before I get it cleaned up enough to go into trunk. You could just pull the code you need from my branch though.

I'll let you know when there's something there that you can play with.

**Comment by wbhart** [comment]
Assuming you are calling nmod_mat_mul directly, you could pull from my omp_to_pthreads branch now. The only file you really need is nmod_mat/mul_classical_threaded.c and to put the prototype for nmod_mat_mul_classical_threaded in nmod_mat.h.

Then you can call nmod_mat_mul_threaded instead of nmod_mat_mul. It takes an extra parameter, which (unless you are paying for supercomputer time) I suggest setting to FLINT_DEFAULT_THREAD_LIMIT or some very large number. This does NOT set the number of threads actually used, just a limit on the number of threads that function can use.

To set the number of threads actually used, call flint_set_num_threads(n) where n is the number of threads you want FLINT to use.

From memory, you also have to call flint_cleanup() at the end of your program if you want a clean valgrind log.

Some notes:

* You will be comparing mul_strassen with mul_classical. The threaded version of the latter is only going to beat the former if you have enough threads. The former has better complexity, the latter is threaded.

* When you increase the number of threads, most servers slow the cores down. You'd also need to pin threads to physical cores to get best performance. Some schedulers also use hyperthreads on the same physical core preferentially to distinct cores. Pinning can help here too.

* There's some other stuff in my branch at the moment that doesn't work at all, e.g. polynomial factoring over Z/pZ. If you don't need this, you can just pull my entire branch. Otherwise just pull the functions you need.

Another option would be to cherry-pick my two commits:

* Thread packed algorithm in mul_classical.
* Add mul_classical_threaded.

Let me know if you have any problems with the code, and let me know if it speeds anything up for you.

**Comment by wbhart** [comment]
I've opened a separate ticket for using BLAS.
