### ISSUE TITLE
fft tests should use `flint_test_multiplier`

### ISSUE THREAD

**Issue by isuruf** [wbhart/flint2#666]

**Comment by wbhart** [comment]
They are pretty long running tests, and I think flint_test_multiplier is 10, which is why I think they don't do this. I could use (flint_test_multiplier + 1)/10

**Comment by isuruf** [comment]
On appveyor we set the multiplier to 1 instead of 10 at https://github.com/wbhart/flint2/blob/trunk/.build_dependencies.cmd#L1

**Comment by wbhart** [comment]
then I could use (flint_test_multiplier + 9)/10. That would have the same effect in both cases.

**Comment by isuruf** [comment]
Wouldn't that map both 1 and 10 to 1? I mentioned this because fft tests take a lot of time compared to others and this could be reduced with the the use of `flint_test_multiplier`. (If it is 10, it should give the current behaviour, but if it is 1, it should run a reduced set of tests)

**Comment by wbhart** [comment]
There's not really any way to reduce the time for the fft tests. They are long running because they have to be in the fft range by definition. The only number less than the current 1 would be 0.

I am really reluctant to reduce it any lower than what we do currently. The FFT is the main engine of Flint and really important to be tested at all values of w and n.

**Comment by isuruf** [comment]
Makes sense.
