### ISSUE TITLE
Doing nmod_poly and fmpz_mod right.

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#769]
I am getting so sick of each nmod_poly and fmpz_mod_poly storing their own context that I have to finally do something about it. It is my understanding that the nmod_poly interface cannot change, i.e. that we are stuck with it forever. How about the fmpz_mod_poly interface? Can these be changed to take an fmpz_mod_ctx_t in the last argument? Regardless of what happens in the official interface, there needs to be an nmod_poly_done_right_t and a fmpz_mod_poly_done_right_t and a small interface implemented for these so fq_t and fq_nmod_t are not the current embarrassment that they are. Fq_zech is great BTW.

**Comment by wbhart** [comment]
It has always been the intention to make a fmpz_mod_t for fmpz_mod_poly.

I'm not hugely in favour of making the interface different in behaviour to
nmod_poly though, since it makes it harder to port things from one to the
other.

I'm also not much in favour of introducing duplicate modules. We have so
much in Flint already, and making it larger, either interface-wise or
code-wise is just not-wise.

Unless there is an absolutely compelling reason to do this, something that
just cannot be done without it, I am not in favour.

But I'll let Fredrik cast the final vote since the size of Flint probably
matters more to him than to me.

Bill.

**Comment by tthsqe12** [comment]
I am sorry that I may have mistyped some things. I meant fmpz_mod_ctx_t in many places. If the fmpz_mod_poly_... fxns are not allowed a ctx object, then there is little hope for fmpz_mod_poly and fq.

**Comment by fredrik-johansson** [comment]
Doing this for fmpz_mod_poly seems ok. Presumably fmpz_mod_mat should be done the same way for consistency.

Personally, I'm still in favor of creating an entirely new mod n type (zmod, say) to subsume both fmpz_mod and nmod, the idea being to using different packed representations internally for vectors, namely 8, 16, 32 or 64 bits per element (64 bits either as a ulong for n <= 2^64 or as an fmpz for n > 2^64). The space savings would be particularly significant for matrices.

**Comment by tthsqe12** [comment]
Then, I will try to do this for fmpz_mod_poly. For example, stuff will look like this:
```
fmpz_mod_poly_init(fmpz_mod_poly_t a, fmpz_mod_ctx_t ctx)
fmpz_mod_poly_add(fmpz_mod_poly_t a, const fmpz_mod_poly_t b, const fmpz_mod_poly_t c, fmpz_mod_ctx_t ctx)
```

**Comment by tthsqe12** [comment]
The absolutely compelling reason to do this for nmod_poly is that I have a bunch of nmod_poly's that need to be memory managed. It is easier to create another wrapper for a nmod_polydr_t which takes an additional context argument. As a bonus, the fq_nmod_t can be a nmod_polydr_t now.
