### ISSUE TITLE
No way to make examples for extension modules

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#84]
Right now, there is no way to build and run example programs for extension modules, such as arb/examples (a hack workaround is to copy the examples to flint2/examples). It would be nice if "make examples" did this automatically.

**Comment by wbhart** [comment]
Flint now builds the examples and puts them in flint2/build/examples. This is not completely robust, in that if more than one extension has an example of the same name, one will overwrite the other. But since there is not an easy way to work out what name an extension has, it's a little difficult to put the examples for each library in its own directory.
