### ISSUE TITLE
fmpz_factor may contain repeated primes which leads to incorrect results in fmpz_euler_phi

### ISSUE THREAD

**Issue by uranix** [wbhart/flint2#859]
Here's an example (using flint 2.6.3, but reproduces on trunk):
```julia
julia> using Nemo
Welcome to Nemo version 0.18.4
Nemo comes with absolutely no warranty whatsoever
julia> p1 = FlintZZ("915362921531129949103")
915362921531129949103
julia> p2 = FlintZZ("1089510157459062950383")
1089510157459062950383
julia> p3 = FlintZZ("593757496188465417973")
593757496188465417973
julia> M = p1 * p2 * p3 * p3
351595097913449634601270339475935310150058173368660630316441860284270835780295023321
julia> phiM_expect = (p1 - 1) * (p2 - 1) * (p3 - 1) * p3
351595097913449634599971372864412846217053413527833633399119155429792393170295104784
julia> factor(M)
1 * 593757496188465417973 * 1089510157459062950383 * 915362921531129949103
# This factorization is misleading, the underlying fmpz_factor_t is
# p = {593757496188465417973, 593757496188465417973, 1089510157459062950383, 915362921531129949103}
# exp = {1, 1, 1, 1}
julia> euler_phi(M)
351595097913449634599379220175528141457746291181718623389408659615995263018144947776
```

**Comment by uranix** [comment]
The problem might be in _fmpz_factor_append 
https://github.com/wbhart/flint2/blob/e56fe2d0bfcf3e1570d51363825347b2bd34de16/fmpz_factor/append.c#L19-L25

This function is called every time a prime factor is found. This factor is simply appended to the list, regardless of whether the incomplete factorization already had it.

Sorting factors might help. Besides it will close https://github.com/wbhart/flint2/issues/603

**Comment by wbhart** [comment]
Wow, this is a pretty serious bug. The logic I decided on is that as soon as a factor is found and primality is checked, the function fmpz_remove should be called to remove the highest possible power of that prime p from the number being factored, then fmpz_factor_append should be called with that power of p. That should result in all the prime factors being distinct.

So I don't think it is necessary to modify _fmpz_factor_append (except to order the factors, as you suggest).

I think we should fix the bug before ordering factors in append, since otherwise it may mask a bug that we are not otherwise aware of.
