### ISSUE TITLE
API changes in 2.7.0

### ISSUE THREAD

**Issue by mahrud** [wbhart/flint2#872]
Seems like 2.7-rc1 includes some major API changes, for instance many functions now need an additional context parameter. Is there a way to keep the changes backwards compatible? If not, could you bump the version 3.0 to make dependency checking easier? At least singular-factory doesn't compile with the new changes.

**Comment by wbhart** [comment]
There's no way to retain backwards compatibility.

But why would 3.0 be any easier to check for than 2.7?

**Comment by mahrud** [comment]
> But why would 3.0 be any easier to check for than 2.7?

For instance, it's a lot easier to use set of routines if the major version is 2 and another set of routines if the major version is 3. More arguments and prose about this is available here: https://semver.org/:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards compatible manner, and
> 3. PATCH version when you make backwards compatible bug fixes.

**Comment by wbhart** [comment]
I think the issue is that 2.7.0 means something different to us than it does to semver. To us it is a major release, but not a major facelift across the whole of Flint. It doesn't refer to backwards compatibility but to how major the release features are.

I am not in favour of making the soname *and* the version refer to the same thing. I have set the soname appropriately for a revision which is not backwards incompatible.

Perhaps @tthsqe12 and @fredrik-johansson have an opinion on this. But historically at least, we have been consistent on what the major version number means.

**Comment by wbhart** [comment]
A precedent for this is the GMP project, which according to the soname numbering in their Makefile.am has not had backwards incompatible changes to their interface since they started using soname numbers. But in that time, the major version number has been incremented from 2 to 6. I think it is clear that Open Source projects do not all use semver for their version numbering.

**Comment by mahrud** [comment]
That makes sense, thanks for the explanation!

**Comment by wbhart** [comment]
You make an important point though, and I think now may be a good opportunity to lay out some plans for an eventual Flint 3.0, which we've been considering for a while. I'll make a post to flint-devel to discuss some of that.

**Comment by tthsqe12** [comment]
Well, if breaking changes require a higher "a" in "a.b.c", then we should have fixed fmpz_mod_mat too. Those currently don't take a context object either.

**Comment by wbhart** [comment]
That module isn't ready to use yet, for sure. It's got very little of any use in it anyway.

But we'll get there.
