### ISSUE TITLE
Test failure in fmpz_lll-test-t-lll_mpf on Windows

### ISSUE THREAD

**Issue by advanpix** [wbhart/flint2#878]
I am building FLINT 2.7.0 on Windows 10 with MSVC (ICC 2018). Compiler shows following warnings:

```
  flint2-2.7.0\fmpz_poly\evaluate_horner_d_2exp.c(54): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *"
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(106): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(190): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(322): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(415): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
```

Then test 684 (fmpz_lll-test-t-lll_mpf) freezes.

I suspect this issue is related to #265.

**Comment by wbhart** [comment]
What version of MPIR are you using?

**Comment by tthsqe12** [comment]
I suspect the culprit here is the
`#define flint_mpf_get_d_2exp mpf_get_d_2exp`
in gmpcompat.h
This line is not correct if using msvc with gmp (not mpir):
`#if defined(__MINGW64__) && !defined(__MPIR_VERSION)`

Since this whole gmpcompat.h is about `sizeof(mp_limb_signed_t)` vs `sizeof(signed long)`, that is what I believe the condition should test.

**Comment by wbhart** [comment]
I think MPIR switched to the same interface as GMP here, and introduced another function for the MPIR version.

**Comment by wbhart** [comment]
What I mean is that Flint relies on the _2exp functions having mp_limb_t arguments. But GMP uses unsigned long instead on Windows. Now it used to be that MPIR changed the interface for these functions to use mp_limb_t instead. But now it does not, and instead uses the same unsigned long as GMP. Instead, it introduces some new functions with mp_limb_t arguments that Flint can use directly, instead of using the GMP ones.

At least that is how I remember things right now.

**Comment by advanpix** [comment]
> What version of MPIR are you using?
MPIR 3.0.0

**Comment by wbhart** [comment]
That's not the problem. That's how things are supposed to be. The function that is called in _fmpz_poly_evaluate_horner_d_2exp2 is flint_mpf_get_d_2exp, not mpf_get_d_2exp. The question is why is it picking up the wrong definition in gmpcompat.h.

**Comment by wbhart** [comment]
I see the problem now. In gmpcompat flint_mpf_get_d_2exp will be #defined to mpf_get_d_2exp in your case, since you are not using GMP or MinGW64.

You are building with MSVC and gmpcompat seems to assume you are using MPIR instead of GMP in that case. I guess at some point this was because Brian Gladman was maintaining the MSVC version via solution files and we didn't support building using MSVC using the main Flint configure. Then along came CMake support and this file has just never been updated.

Moreover, as I said, from MPIR 3.0.0 the MPIR prototype of this function reverted to the same as in GMP which means the special gmpcompat version is required with MPIR 3.0.0 on Windows. So this is in fact a convergence of two separate bugs.

The question is, how on earth is the CMake build passing on MSVC? That doesn't seem possible, and yet it currently is:

https://ci.appveyor.com/project/wbhart/flint2/builds/37116631/job/9u26v0yp6qw01d08

That's concerning in and of itself. I guess the upper half of the long long just happens to be zero maybe. But I am surprised there are not many more failures.

Anyhow, the solution seems to be that we should do what @tthsqe12 suggests (though for different reasons I believe), and use the gmpcompat versions of all those functions whenever MPIR is being used and sizeof(long) != sizeof(slong).

Secondly, whenever MPIR < 3.0.0 is being used and sizeof(long) != sizeof(slong) we do not need this specific function to use the special gmpcompat version. On the other hand, this change is actually not important, since the gmpcompat version is essentially the one MPIR < 3.0.0 uses.

I will make the change @tthsqe12 suggests on a branch and see if all our tests still pass.

**Comment by advanpix** [comment]
Thank you for the detailed investigation and explanation.
I have added the changes to gmpcompat, but Intel Compiler gets angry on using sizeof in the #if:" 

`#if sizeof(slong) != sizeof(long)`

with following error message:
 `error : function call is not allowed in a constant expression`.

After quick googling, I see that this is endemic issue with Intel compilers (and not yet fixed). 
Is there an easy way to fix this without the sizeof in macro (to pacify the ICC)?

**Comment by wbhart** [comment]
Yes, see the open PR #880 above, which seems to fix the issue (though testing is still underway). I will merge this into trunk and flint-2.7 branches later today if all goes well.

**Comment by advanpix** [comment]
With the newest changes to gmpcompat.h all tests have passed, except for 
```
The following tests FAILED:
        1831 - fmpz_mpoly-test-t-repack_bits (SEGFAULT)
```

**Comment by wbhart** [comment]
We aren't seeing this failure. I did just make some additional corrections a few hours ago, so check you actually have the latest. But probably they only affect 32 bit machines anyway.

Is it possible your machine is running out of memory?

**Comment by tthsqe12** [comment]
If 1831 continues to segfault, I should have a look at it.

**Comment by advanpix** [comment]
@"Is it possible your machine is running out of memory?"
No, my computer has 64GB with 50GB free.

Do you use MSVC compiler? I use Intel compiler, maybe this is the difference.
Also I use vanilla  FLINT 2.7.0 from releases (with gmpcompat.h copied over the old header) without any recent commits.
Is it better to test master?

**Comment by wbhart** [comment]
Only @tthsqe12 could answer that. There are other fixes, but I don't know if they could cause this segfault.

I will let @tthsqe12 deal with this. I'll hold the release.

**Comment by advanpix** [comment]
Ok, meanwhile, I will build & run tests from the master.

**Comment by tthsqe12** [comment]
yes, do everything from master

**Comment by wbhart** [comment]
This PR closed automatically when I committed the fix for the original issue. Can you open a new issue if there are still problems, or let us know here if not. Of course we have no master branch, but instead use trunk.
