### ISSUE TITLE
test mul_blas takes *really* very long, and longer the more threads!

### ISSUE THREAD

**Issue by tornaria** [wbhart/flint2#920]
- Using my distro `openblas-devel`.
- Download `flint-2.7.1.tar.gz`
- `./configure --with-blas=/usr/include/openblas && make`
- `make check MOD=nmod_mat:mul_blas`
- afterwards I just run `time build/nmod_mat/test/t-mul_blas`

I have tried 3 different boxes (I compiled ONCE in one box, then shared the files -- the openblas shared library is also exactly the same, coming from the distribution).

1. BOX A (desktop, core i7-9700 = skylake, 8c/8t). In this box, `t-mul_blas` takes 20s wall / 150s cpu. 

2. BOX B (server, xeon E5520 x2 = nehalem, 8c/16t). Here it took 155s wall / 1690s cpu.

3. BOX C (server, xeon 6240 x 2 = cascade lake, 36c/72t). Here it took 303s wall / 12236s cpu (that's 3.5 hours).

As a compare: compiling without openblas the test takes on the order of 5s wall / 5s cpu.

Setting OMP_NUM_THREADS=1 results in A: 13s wall / 18s cpu, B: 34s wall / 45s cpu, C: 18s wall / 27s cpu.

**Comment by wbhart** [comment]
Sounds like some long testing runs were not reverted before pushing. Thanks for the report.

Perhaps @tthsqe12 can take a look when he is back on deck after Easter.

**Comment by tthsqe12** [comment]
This has nothing to do with long tests, and I don't think this is necessarily our fault:

> Setting OMP_NUM_THREADS=1 results in A: 13s wall / 18s cpu, B: 34s wall / 45s cpu, C: 18s wall / 27s cpu.
Bingo!

After some thought and discussions with others, I decided not to touch the openblas thread count from within flint.
In the extreme, I though any reasonable blas implementation would take care not to use 72 threads to multiply two 2x2 matrices, but it looks like this is not the case!

**Comment by tornaria** [comment]
What's the way out of this, other than not enabling openblas in flint?

**Comment by wbhart** [comment]
I guess it is using OpenMP given that OMP_NUM_THREADS seems to control the behaviour. Could it be that using openblas-pthreads will make the problem go away @tthsqe12 ?

**Comment by wbhart** [comment]
Anyway, can't we modify the tests to prevent them running with a gazillion threads on small matrices? Surely the code is only useful if it only uses BLAS in realistic regimes.

And anyway, I thought we were using openblas_set_num_threads in our test code.

**Comment by tthsqe12** [comment]
It is important to understand how the flint code works.
nmod_mat_mul_blas (which is what is being tested) can use blas on any size matrices (even 1x1).
nmod_mat_mul tries to be intelligent and _not_ call nmod_mat_mul_blas if the matrices are too small.

No where ever do I query or set the number threads for blas, partly because these seem to be openblas specific extensions and partly because it is a huge can of worms.

**Comment by wbhart** [comment]
Right, but it seems to be a massive problem that BLAS takes weeks to run the tests because of very small matrices being tested. We need to resolve this if possible. We can't just tell users to turn BLAS off so they can run tests. That defeats the purpose of having tests.

What would you suggest so that we can resolve this?

**Comment by tthsqe12** [comment]
The openblas people are still working on it
https://github.com/xianyi/OpenBLAS/issues/1881

**Comment by wbhart** [comment]
I don't know if a burst of activity back in 2018 counts as "working on it".

**Comment by tornaria** [comment]
> Right, but it seems to be a massive problem that BLAS takes weeks to run the tests because of very small matrices being tested. We need to resolve this if possible. We can't just tell users to turn BLAS off so they can run tests. That defeats the purpose of having tests.

Somewhat worse: it gives me the (I assume incorrect) impression that I should disable BLAS because its performance is inversely proportional to the number of threads.

It would be nice if the test demonstrated that using openblas with 36 core is worth it. If not, I'll keep parallelizing my outer loops (best case: have 36 different projects that need computation at any given time  🤣).

**Comment by wbhart** [comment]
@tornaria You shouldn't call the blas functions directly. They are already called in an optimal way by the usual functions (if BLAS is available).

The issue here is that we test the actual blas function directly, rather than coincidentally through the other functions that make use of it. But unfortunately openblas does stupid things like using many threads on very small multiplications and then getting into some kind of weird condition.

It is definitely worth using BLAS when available, as our benchmarks have demonstrated. But this is still being worked on actively by myself and @tthsqe12 so not everything is 100% optimal yet.

I totally sympathise with you over the very long running test. That's just awful. That's a separate issue though to using openblas optimally in the library. It really does depend on the BLAS people.

**Comment by tornaria** [comment]
I understand it's desirable to test `mul_blas` directly and for small matrices, but maybe not 10k of them with default number of threads?

Perhaps a compromise could be:
- test a few small matrices with default threads
- test some more small and intermediate matrices with <= 4 threads
- test a few large matrices with "large" depending on the number of threads in such a way that the wall time is (very roughly) constant.

The third is test would excercise sizes where it's worth using blas with many threads, does that make sense?

---

At the very least: print a warning that the mul_blas test will take long.

After all, it was only 5 minutes wall, but when I'm looking at make check I see lots of tests running swiftly (I make check -j 36) and then this thing seems to be stuck and when I see the process has already used 2 hours of cpu time I assume it will never finish. I could have been more patient if I had knew :-) In fact, I started writing an issue about "t-mul_blas doesn't finish" but it took me more than 5 minutes to write so it finished... 😂

**Comment by wbhart** [comment]
We discussed this today at our Flint Friday meeting and decided to implement pretty much what you suggested @tornaria 

@tthsqe12 will take care of this soon and it will be in our next development release, which should be a few days or maybe a week or two away. Flint-2.8 itself is not scheduled for release for a few months, ostensibly "before" summer.
