### ISSUE TITLE
Make fmpz_poly_factor provably correct wrt leading coefficients

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#954]
The leading coefficient correction all throughout fmpz_poly_factor is suspect.

https://github.com/wbhart/flint2/blob/708f963d52e1151b1c9174272e27af5898a81450/fmpz_poly_factor/factor_zassenhaus.c#L193-L198

Candidate factors are constructed with the same leading coefficient as the original polynomial, but this is not considered when setting up lifting bounds.

take f=(2x+1)(x-2)=2x^2-3x-2
It is easy to see that B=3 is bound on any divisor of f
but for g=x-2, lc(f)*g/lc(g) = 2x-4, which has a coefficient bigger than B

Why haven't we noticed this? The bounds are so pessimistic.

**Comment by wbhart** [comment]
The changes to the LLL algorithm for factoring polynomials over the integers are described in Mark van Hoeij's paper, "Factoring Polynomials and the Knapsack Problem", on page 184, in section 2.3 part 4.

There are two main parts:

1) He notes that if f is the nonmonic polynomial being factored with leading coefficient C_N and g is a monic polynomial factor in Q[x] not in Z[x] then Tr_i(g) is no longer in Z. This means one must use C_N^i*Tr_i(g) instead, as that is in Z.

2) As per the Berlekamp-Zassenhaus algorithm, one does not work with prod_i f_i^{v_i} smod p^a, but with C_N prod_i f_i^{v_i} smod p^a, since we know that the final polynomial has to have leading coefficient C_N. In other words we scale the padic information by C_N and look for monic factors over Q padically.

There's no mention of changing the lifting bound in the nonmonic case.

Note we use CLD's in our implementation which need an adjustment like 1.

**Comment by wbhart** [comment]
Landau-Mignotte does not require the original polynomial to be monic. It works for arbitrary polynomials.

Let's see, what other lifting bounds do we use here....

**Comment by wbhart** [comment]
I don't see the issue here. It think the multiplication by two plus 1 is for signs as LM is for the absolute value of the coefficient. It's not a leading coefficient correction, which isn't needed.

**Comment by wbhart** [comment]
Nevertheless I see the problem with our implementation. Whilst any factor g might be bounded by LM, C_N g is not. We won't get something over Z. This actually seems to be more or less an omission from van Hoeij's original paper if I am not mistaken.

I will change the code to multiply the lifting bound by C_N in all cases.

**Comment by tthsqe12** [comment]
ok

**Comment by wbhart** [comment]
Fixed in trunk.

**Comment by fredrik-johansson** [comment]
Is the patch correct when the leading coefficient is negative?

**Comment by tthsqe12** [comment]
it looks dodgy because fmpz_clog_ui assume positive input.

**Comment by wbhart** [comment]
No idea, but I fixed it.
