### ISSUE TITLE
endianness config needs fixing

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#985]
The newest flint 2.8 jll binaries are completely broken on windows and macos (https://github.com/Nemocas/Nemo.jl/pull/1144).

The reason is the following horrific line in the windows/macos log:
```
Testing big endian...yes
```
All of the floats are backwards!

The endianness configurator is incompatible with cross compilation.
Endianness is not an optional feature that can be enabled by a successful compile + run. It has to be correct regardless of the return code of
```
build/test-endian > /dev/null 2>&1
```

**Comment by fingolfin** [comment]
The problem is that during cross compilation, we can not execute test programs. Therefore tools like `autoconf` typically have two sets of tests: one that can be used when not cross compiling, and a fallback for cross compilation. The latter typically goes like this: first look for one of a bunch of preprocessor defines indicating endianess; see e.g. https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html for `__BYTE_ORDER__` and friends, added in GCC 4.6 and also supported in clang. Other common symbols for this  include `__BIG_ENDIAN__` and `__LITTLE_ENDIAN__`, both also supported by GCC and clang (not sure how official that is, though).

If that doesn't work (because the compiler does not define any of these), one can fallback to compiling a binary with a certain pattern in it and then using `grep` to check for it in the resulting executable. The following is from ScummVM, but it is directly based on the corresponding code in autoconf:
```
echo_n "Checking endianness... "
cat > tmp_endianness_check.cpp << EOF
__attribute__ ((used)) unsigned short ascii_mm[] = { 0x4249, 0x4765, 0x6E44, 0x6961, 0x6E53, 0x7953, 0 };
__attribute__ ((used)) unsigned short ascii_ii[] = { 0x694C, 0x5454, 0x656C, 0x6E45, 0x6944, 0x6E61, 0 };
const char * _ascii() { char* s = (char*) ascii_mm; s = (char*) ascii_ii; return s; }
__attribute__ ((used)) unsigned short ebcdic_ii[] = { 0x89D3, 0xE3E3, 0x8593, 0x95C5, 0x89C4, 0x9581, 0 };
__attribute__ ((used)) unsigned short ebcdic_mm[] = { 0xC2C9, 0xC785, 0x95C4, 0x8981, 0x95E2, 0xA8E2, 0 };
const char * _ebcdic() { char* s = (char*) ebcdic_mm; s = (char*) ebcdic_ii; return s; }
int main() { _ascii (); _ebcdic (); return 0; }
EOF
$CXX $LDFLAGS $CXXFLAGS -o $TMPO$HOSTEXEEXT tmp_endianness_check.cpp >> "$TMPLOG" 2>&1
if $_strings $TMPO$HOSTEXEEXT 2>> "$TMPLOG"| grep BIGenDianSyS >/dev/null; then
	_endian=big
elif $_strings $TMPO$HOSTEXEEXT 2>> "$TMPLOG" | grep LiTTleEnDian >/dev/null; then
	_endian=little
fi
echo $_endian;
cc_check_clean tmp_endianness_check.cpp tmp_endianness_check.dwo

case $_endian in
	big)
		add_line_to_config_h '#undef SCUMM_LITTLE_ENDIAN'
		add_line_to_config_h '#define SCUMM_BIG_ENDIAN'
		;;
	little)
		add_line_to_config_h '#define SCUMM_LITTLE_ENDIAN'
		add_line_to_config_h '#undef SCUMM_BIG_ENDIAN'
		;;
	*)
		exit 1
		;;
esac
```

In practice, this always works; ScummVM runs on far more platforms and systems than FLINT ever will.

Until Flint is properly fixed and has a new release, we can simply add a patch for Flint to the `Flint_JLL` builder which removes the test for endianess, and hardcode it to "little endian", as that's what all our supported archs have anyway.

CC @thofman @benlorenz

**Comment by tthsqe12** [comment]
Thanks for all of the options! running grep on a executable sounds a bit better then trying to run a .exe ...
